// <auto-generated />
using System;
using CareLoop.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareLoop.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CareLoopDbContext))]
    partial class CareLoopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareLoop.Domain.CareCases.CareCase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DiagnosticOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_order_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_care_cases");

                    b.HasIndex("DiagnosticOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_care_cases_diagnostic_order_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_care_cases_patient_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_care_cases_status_created_at");

                    b.ToTable("care_cases", (string)null);
                });

            modelBuilder.Entity("CareLoop.Domain.CareCases.CareCaseEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_case_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_care_case_events");

                    b.HasIndex("CareCaseId")
                        .HasDatabaseName("ix_care_case_events_care_case_id");

                    b.ToTable("care_case_events", (string)null);
                });

            modelBuilder.Entity("CareLoop.Domain.Communications.ContactAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<Guid>("CareCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_case_id");

                    b.Property<int>("Method")
                        .HasColumnType("integer")
                        .HasColumnName("method");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<bool>("Successful")
                        .HasColumnType("boolean")
                        .HasColumnName("successful");

                    b.HasKey("Id")
                        .HasName("pk_contact_attempts");

                    b.HasIndex("CareCaseId")
                        .HasDatabaseName("ix_contact_attempts_care_case_id");

                    b.ToTable("contact_attempts", (string)null);
                });

            modelBuilder.Entity("CareLoop.Domain.Diagnostics.DiagnosticOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OrderedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ordered_at");

                    b.Property<Guid>("OrderedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("ordered_by");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("test_name");

                    b.HasKey("Id")
                        .HasName("pk_diagnostic_orders");

                    b.HasIndex("OrderedAt")
                        .HasDatabaseName("ix_diagnostic_orders_ordered_at");

                    b.ToTable("diagnostic_orders", (string)null);
                });

            modelBuilder.Entity("CareLoop.Domain.Diagnostics.DiagnosticResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_case_id");

                    b.Property<Guid>("DiagnosticOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("diagnostic_order_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_diagnostic_results");

                    b.HasIndex("CareCaseId")
                        .IsUnique()
                        .HasDatabaseName("ix_diagnostic_results_care_case_id");

                    b.HasIndex("DiagnosticOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_diagnostic_results_diagnostic_order_id");

                    b.ToTable("diagnostic_results", (string)null);
                });

            modelBuilder.Entity("CareLoop.Domain.Escalations.Escalation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_case_id");

                    b.Property<DateTimeOffset>("EscalatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("escalated_at");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_escalations");

                    b.HasIndex("CareCaseId")
                        .HasDatabaseName("ix_escalations_care_case_id");

                    b.ToTable("escalations", (string)null);
                });

            modelBuilder.Entity("CareLoop.Domain.FollowUps.FollowUpAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<Guid>("CareCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_case_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_follow_up_actions");

                    b.HasIndex("CareCaseId")
                        .HasDatabaseName("ix_follow_up_actions_care_case_id");

                    b.HasIndex("Status", "DueAt")
                        .HasDatabaseName("ix_follow_up_actions_status_due_at");

                    b.ToTable("follow_up_actions", (string)null);
                });

            modelBuilder.Entity("CareLoop.Domain.Patients.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MedicalRecordNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("medical_record_number");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.HasIndex("MedicalRecordNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_patients_medical_record_number");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("CareLoop.Domain.Reviews.ClinicalReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_case_id");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.HasKey("Id")
                        .HasName("pk_clinical_reviews");

                    b.HasIndex("CareCaseId")
                        .IsUnique()
                        .HasDatabaseName("ix_clinical_reviews_care_case_id");

                    b.ToTable("clinical_reviews", (string)null);
                });

            modelBuilder.Entity("CareLoop.Domain.CareCases.CareCase", b =>
                {
                    b.HasOne("CareLoop.Domain.Diagnostics.DiagnosticOrder", "DiagnosticOrder")
                        .WithOne()
                        .HasForeignKey("CareLoop.Domain.CareCases.CareCase", "DiagnosticOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_care_cases_diagnostic_orders_diagnostic_order_id");

                    b.HasOne("CareLoop.Domain.Patients.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_care_cases_patients_patient_id");

                    b.Navigation("DiagnosticOrder");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CareLoop.Domain.CareCases.CareCaseEvent", b =>
                {
                    b.HasOne("CareLoop.Domain.CareCases.CareCase", null)
                        .WithMany("Events")
                        .HasForeignKey("CareCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_care_case_events_care_cases_care_case_id");
                });

            modelBuilder.Entity("CareLoop.Domain.Communications.ContactAttempt", b =>
                {
                    b.HasOne("CareLoop.Domain.CareCases.CareCase", null)
                        .WithMany("ContactAttempts")
                        .HasForeignKey("CareCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_attempts_care_cases_care_case_id");
                });

            modelBuilder.Entity("CareLoop.Domain.Diagnostics.DiagnosticResult", b =>
                {
                    b.HasOne("CareLoop.Domain.CareCases.CareCase", null)
                        .WithOne("DiagnosticResult")
                        .HasForeignKey("CareLoop.Domain.Diagnostics.DiagnosticResult", "CareCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diagnostic_results_care_cases_care_case_id");

                    b.HasOne("CareLoop.Domain.Diagnostics.DiagnosticOrder", null)
                        .WithOne()
                        .HasForeignKey("CareLoop.Domain.Diagnostics.DiagnosticResult", "DiagnosticOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_diagnostic_results_diagnostic_orders_diagnostic_order_id");
                });

            modelBuilder.Entity("CareLoop.Domain.Escalations.Escalation", b =>
                {
                    b.HasOne("CareLoop.Domain.CareCases.CareCase", null)
                        .WithMany("Escalations")
                        .HasForeignKey("CareCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_escalations_care_cases_care_case_id");
                });

            modelBuilder.Entity("CareLoop.Domain.FollowUps.FollowUpAction", b =>
                {
                    b.HasOne("CareLoop.Domain.CareCases.CareCase", null)
                        .WithMany("FollowUpActions")
                        .HasForeignKey("CareCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_follow_up_actions_care_cases_care_case_id");
                });

            modelBuilder.Entity("CareLoop.Domain.Reviews.ClinicalReview", b =>
                {
                    b.HasOne("CareLoop.Domain.CareCases.CareCase", null)
                        .WithOne("ClinicalReview")
                        .HasForeignKey("CareLoop.Domain.Reviews.ClinicalReview", "CareCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clinical_reviews_care_cases_care_case_id");
                });

            modelBuilder.Entity("CareLoop.Domain.CareCases.CareCase", b =>
                {
                    b.Navigation("ClinicalReview");

                    b.Navigation("ContactAttempts");

                    b.Navigation("DiagnosticResult");

                    b.Navigation("Escalations");

                    b.Navigation("Events");

                    b.Navigation("FollowUpActions");
                });
#pragma warning restore 612, 618
        }
    }
}
